SELECT
	CAR_NAME,
	YEAR_OF_MANUFACTURING,
	FUEL_TYPE,
	KMS_RUN,
	SALE_PRICE,
	CITY,
	TIMES_VIEWED,
	BODY_TYPE,
	TRANSMISSION,
	VARIANT,
	ASSURED_BUY,
	REGISTERED_CITY,
	REGISTERED_STATE,
	IS_HOT,
	RTO,
	[SOURCE],
	MAKE,
	MODEL,
	CAR_AVAILABILITY,
	TOTAL_OWNERS,
	BROKER_QUOTE,
	ORIGINAL_PRICE,
	CAR_RATING,
	AD_CREATED_ON_DATE,
	AD_CREATED_AT_TIME,
	FITNESS_CERTIFICATE,
	EMI_STARTS_FROM,
	BOOKING_DOWN_PAYMENT,
	RESERVED,
	WARRANTY_AVAILABLE
FROM CAR;

---4.1 Pricing & Valuation Analysis
---What is the average depreciation rate for different models (e.g., Wagon R, Swift, Alto K10) over time?

-- Calculate average depreciation for each car model
SELECT
	ISNULL(MODEL,'UNKNOWN') AS MODEL,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/
				NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT,
	ROUND(AVG(ORIGINAL_PRICE-SALE_PRICE),2) AS AVG_DEPRECIATION_AMOUNT
FROM CAR
WHERE ORIGINAL_PRICE IS NOT NULL AND SALE_PRICE IS NOT NULL
GROUP BY MODEL
ORDER BY AVG_DEPRECIATION_PERCENT DESC;

-- Trend of depreciation over manufacturing years for a specific model(Wagon)
SELECT
	YEAR_OF_MANUFACTURING,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/
		NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE MODEL = 'WAGON R'
	AND ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY YEAR_OF_MANUFACTURING
ORDER BY YEAR_OF_MANUFACTURING DESC;

-- Trend of depreciation over manufacturing years for a specific model(Swift)
SELECT
	YEAR_OF_MANUFACTURING,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/
		NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE MODEL = 'SWIFT'
	AND ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY YEAR_OF_MANUFACTURING
ORDER BY YEAR_OF_MANUFACTURING DESC;

-- Trend of depreciation over manufacturing years for a specific model(Swift)
SELECT
	YEAR_OF_MANUFACTURING,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/
		NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE MODEL = 'ALTO K10'
	AND ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY YEAR_OF_MANUFACTURING
ORDER BY YEAR_OF_MANUFACTURING DESC;

---How do factors like Kms_Run, Year_Of_Manufacturing, Fuel_Type, and City impact the Sale_Price?

-- Relationship between kilometers driven and sale price
SELECT
	CASE
		WHEN KMS_RUN < 20000 THEN '< 20K'
		WHEN KMS_RUN BETWEEN 20000 AND 50000 THEN '20K-50K'
		WHEN KMS_RUN BETWEEN 50001 AND 100000 THEN '50K-100K'
		ELSE '100K+'
	END AS KMS_CATEGORY,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE) * 100.0 / NULLIF (ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE KMS_RUN IS NOT NULL
	AND ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY 
	CASE
		WHEN KMS_RUN < 20000 THEN '< 20K'
		WHEN KMS_RUN BETWEEN 20000 AND 50000 THEN '20K-50K'
		WHEN KMS_RUN BETWEEN 50001 AND 100000 THEN '50K-100K'
		ELSE '100K+'
	END
ORDER BY AVG_SALE_PRICE DESC;

-- Impact of manufacturing year on Sale_Price and depreciation
SELECT
	YEAR_OF_MANUFACTURING,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE,
	ROUND(AVG(KMS_RUN),2) AS AVG_KMS_RUN,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE) *100.0 / NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE YEAR_OF_MANUFACTURING IS NOT NULL
	AND SALE_PRICE IS NOT NULL
	AND ORIGINAL_PRICE IS NOT NULL
GROUP BY YEAR_OF_MANUFACTURING
ORDER BY YEAR_OF_MANUFACTURING DESC;

-- Impact of fuel type on Sale_Price and depreciation
SELECT
	FUEL_TYPE,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE,
	ROUND(AVG(KMS_RUN),2) AS AVG_KMS_RUN,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100.0/NULLIF (ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE FUEL_TYPE IS NOT NULL
	AND ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY FUEL_TYPE
ORDER BY AVG_SALE_PRICE DESC;

-- Impact of City on Sale_Price and depreciation
SELECT
	CITY,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE,
	ROUND(AVG(KMS_RUN),2) AS AVG_KMS_RUN,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)* 100.0 / NULLIF (ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT
FROM CAR
WHERE CITY IS NOT NULL
	AND SALE_PRICE IS NOT NULL
	AND ORIGINAL_PRICE IS NOT NULL
GROUP BY CITY
ORDER BY AVG_SALE_PRICE DESC;

---Can we build a model to predict the fair market value (Sale_Price) of a car based on its attributes?
SELECT
	MODEL,
	FUEL_TYPE,
	YEAR_OF_MANUFACTURING,
	TRANSMISSION,
	ROUND(AVG(SALE_PRICE),2) AS PREDICTED_FAIR_MAKET_VALUE
FROM CAR
WHERE SALE_PRICE IS NOT NULL
GROUP BY MODEL,
	YEAR_OF_MANUFACTURING,
	FUEL_TYPE,
	TRANSMISSION
ORDER BY PREDICTED_FAIR_MAKET_VALUE DESC;

---What is the typical difference between the Original_Price and the Sale_Price (depreciation)?
SELECT
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(ORIGINAL_PRICE-SALE_PRICE),2) AS DEPRECIATION_AMOUNT,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/NULLIF (ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT,
	MIN(ORIGINAL_PRICE-SALE_PRICE) AS MIN_DEPRECIATION_AMOUNT,
	MAX(ORIGINAL_PRICE-SALE_PRICE) AS MAX_DEPRECIATION_AMOUNT
FROM CAR
WHERE ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL;

---4.2 Geographic & Demographic Analysis
---Which cities (City, Registered_City) have the highest volume of listings and the highest average prices?
SELECT
	CITY,
	REGISTERED_CITY,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(ORIGINAL_PRICE-SALE_PRICE),2) AS AVG_DEPRECIATION_AMOUNT,
	ROUND(AVG((ORIGINAL_PRICE-SALE_PRICE)*100/NULLIF(ORIGINAL_PRICE,0)),2) AS AVG_DEPRECIATION_PERCENT,
	MIN(ORIGINAL_PRICE-SALE_PRICE) AS MIN_DEPRECIATION_AMOUNT,
	MAX(ORIGINAL_PRICE-SALE_PRICE) AS MAX_DEPRECIATION_AMOUNT
FROM CAR
WHERE ORIGINAL_PRICE IS NOT NULL
	AND SALE_PRICE IS NOT NULL
	AND REGISTERED_CITY IS NOT NULL
GROUP BY CITY, REGISTERED_CITY;

---Are there specific models that are more popular in certain cities or states?

-- Top models in each City
WITH RANKEDMODELS AS(
	SELECT
		CITY,
		MODEL,
		COUNT(*) AS TOTAL_LISTINGS,
		ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY COUNT(*) DESC) AS RANKINCITY
	FROM CAR
	WHERE CITY IS NOT NULL 
		AND MODEL IS NOT NULL
	GROUP BY CITY, MODEL
)
SELECT
	CITY,
	MODEL,
	TOTAL_LISTINGS
FROM RANKEDMODELS
WHERE RANKINCITY<= 5
ORDER BY TOTAL_LISTINGS DESC;

-- Top models in each State
WITH RANKEDMODELS AS(
			SELECT
				REGISTERED_STATE,
				MODEL,
				COUNT(*)  AS TOTAL_LISTINGS,
				ROW_NUMBER() OVER(PARTITION BY REGISTERED_STATE ORDER BY COUNT(*) DESC) AS RANKINSTATE
			FROM CAR
			WHERE REGISTERED_STATE IS NOT NULL
				AND MODEL IS NOT NULL
			GROUP BY REGISTERED_STATE,MODEL
)
SELECT
	REGISTERED_STATE,
	MODEL,
	TOTAL_LISTINGS
FROM RANKEDMODELS
WHERE RANKINSTATE<= 5
ORDER BY TOTAL_LISTINGS DESC;

---Is there a price difference for the same car model in different cities?

-- Average sale price of each car model across cities
SELECT
	CITY,
	MODEL,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE
FROM CAR
WHERE MODEL IS NOT NULL
	AND CITY IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY MODEL,CITY
ORDER BY MODEL,AVG_SALE_PRICE DESC;

-- Price variation of each model across cities
SELECT TOP 100
	MODEL,
	ROUND(MIN(AVG_SALE_PRICE),2) AS MIN_CITY_AVG_SALE_PRICE,
	ROUND(MAX(AVG_SALE_PRICE),2) AS MAX_CITY_SALE_PRICE,
	ROUND(MAX(AVG_SALE_PRICE)-MIN(AVG_SALE_PRICE),2) AS PRICE_DIFFERENCE
FROM (
	SELECT
		MODEL,
		CITY,
		AVG(SALE_PRICE) AS AVG_SALE_PRICE
	FROM CAR
	WHERE MODEL IS NOT NULL
		AND CITY IS NOT NULL
		AND SALE_PRICE IS NOT NULL
	GROUP BY MODEL,CITY
)
AS CITY_PRICES
GROUP BY MODEL
ORDER BY PRICE_DIFFERENCE DESC;

-- Compare prices of one specific model across cities
SELECT
	CITY,
	COUNT(*) AS TOTAL_LISTINGS,
	ROUND(AVG(SALE_PRICE),2) AS AVG_SALE_PRICE
FROM CAR
WHERE MODEL = 'SWIFT'
	AND CITY IS NOT NULL
	AND SALE_PRICE IS NOT NULL
GROUP BY CITY
ORDER BY AVG_SALE_PRICE DESC;

---4.3 Customer Engagement & Sales Performance
---Which car features (e.g., Transmission, Fuel_Type, Assured_Buy) lead to higher Times_Viewed?
SELECT
	TRANSMISSION,
	FUEL_TYPE,
	ASSURED_BUY,
	COUNT(TIMES_VIEWED) AS TOTAL_VIEWS
FROM CAR
GROUP BY TRANSMISSION,FUEL_TYPE,ASSURED_BUY
ORDER BY TOTAL_VIEWS DESC;

---Do Is_Hot or Assured_Buy cars command a price premium and get more views?
SELECT
	CASE
		WHEN IS_HOT = 'TRUE' AND ASSURED_BUY = '1' THEN 'HOT & ASSURED'
		WHEN IS_HOT = 'TRUE' AND ASSURED_BUY = '0' THEN 'HOT'
		WHEN IS_HOT = 'FALSE' AND ASSURED_BUY = '1' THEN 'ASSURED'
		ELSE 'STANDARD LISTING'
	END AS LISTING_TYPE,
	COUNT(*) AS TOTAL_CARS,

	 -- Price analysis
    AVG(CAST(SALE_PRICE AS FLOAT)) AS AVG_SALE_PRICE,
    MIN(CAST(SALE_PRICE AS FLOAT)) AS MIN_SALE_PRICE,
    MAX(CAST(SALE_PRICE AS FLOAT)) AS MAX_SALE_PRICE,

	-- Views analysis
    AVG(CAST(TIMES_VIEWED AS FLOAT)) AS AVG_VIEWS,
    MIN(CAST(TIMES_VIEWED AS FLOAT)) AS MIN_VIEWS,
    MAX(CAST(TIMES_VIEWED AS FLOAT)) AS MAX_VIEWS,

	-- Price premium calculation vs standard listings
    ((AVG(CAST(SALE_PRICE AS FLOAT)) - 
     (SELECT AVG(CAST(SALE_PRICE AS FLOAT)) 
      FROM CAR 
      WHERE IS_HOT = 'FALSE' AND ASSURED_BUY = 'FALSE')) / 
     (SELECT AVG(CAST(SALE_PRICE AS FLOAT)) 
      FROM CAR 
      WHERE IS_HOT = 'FALSE' AND ASSURED_BUY = 'FALSE')) * 100 AS PRICE_PREMIUM_PERCENT,

	-- Views premium calculation vs standard listings
    ((AVG(CAST(TIMES_VIEWED AS FLOAT)) - 
     (SELECT AVG(CAST(TIMES_VIEWED AS FLOAT)) 
      FROM CAR 
      WHERE IS_HOT = 'FALSE' AND ASSURED_BUY = 'FALSE')) / 
     (SELECT AVG(CAST(TIMES_VIEWED AS FLOAT)) 
      FROM CAR 
      WHERE IS_HOT = 'FALSE' AND ASSURED_BUY = 'FALSE')) * 100 AS VIEWS_PREMIUM_PERCENT,


	-- Quality controls
    ROUND(AVG(CAST(YEAR_OF_MANUFACTURING AS FLOAT)),0) AS AVG_MANUFACTURING_YEAR,
    AVG(CAST(KMS_RUN AS FLOAT)) AS AVG_KMS_RUN,

	-- Market segment distribution
	COUNT(CASE WHEN BODY_TYPE = 'HATCHBACK' THEN 1 END) AS HATCHBACK_COUNT,
	COUNT(CASE WHEN BODY_TYPE = 'SUV' THEN 1 END) AS SUV_COUNT,
	COUNT(CASE WHEN BODY_TYPE = 'SEDAN' THEN 1 END) AS SEDAN_COUNT
FROM CAR
WHERE ISNUMERIC(SALE_PRICE) = 1 
  AND ISNUMERIC(TIMES_VIEWED) = 1
  AND ISNUMERIC(YEAR_OF_MANUFACTURING) = 1
  AND ISNUMERIC(KMS_RUN) = 1
GROUP BY
	CASE
		WHEN IS_HOT = 'TRUE' AND ASSURED_BUY = '1' THEN 'HOT & ASSURED'
		WHEN IS_HOT = 'TRUE' AND ASSURED_BUY = '0' THEN 'HOT'
		WHEN IS_HOT = 'FALSE' AND ASSURED_BUY = '1' THEN 'ASSURED'
		ELSE 'STANDARD LISTING'
	END
ORDER BY PRICE_PREMIUM_PERCENT DESC;

---4.4 Vehicle Specification Analysis:
---What is the market share of different Fuel_Types and Transmission types?

--Market share of different Fuel_Types
SELECT
	FUEL_TYPE,
	COUNT(*) AS TOTAL_CARS,
	ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM CAR),2) AS MARKET_SHARE_PERCENT
FROM CAR
WHERE FUEL_TYPE IS NOT NULL
GROUP BY FUEL_TYPE
ORDER BY MARKET_SHARE_PERCENT DESC;

--Market share of different Transmission types
SELECT
	TRANSMISSION,
	COUNT(*) AS TOTAL_CARS,
	ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM CAR),2) AS MARKET_SHARE_PERCENT
FROM CAR
WHERE TRANSMISSION IS NOT NULL
GROUP BY TRANSMISSION
ORDER BY MARKET_SHARE_PERCENT DESC;

---How does the Total_Owners field affect the sale price?
SELECT
	TOTAL_OWNERS,
	AVG(SALE_PRICE) AS AVG_SALE_PRICE
FROM CAR
GROUP BY TOTAL_OWNERS
ORDER BY TOTAL_OWNERS;

---Are cars with Warranty_Available or Fitness_Certificate priced higher?
SELECT
	WARRANTY_AVAILABLE,
	FITNESS_CERTIFICATE,
	AVG(SALE_PRICE) AS AVG_SALE_PRICE,
	COUNT(*) AS TOTAL_CARS
FROM CAR
GROUP BY WARRANTY_AVAILABLE, FITNESS_CERTIFICATE
ORDER BY WARRANTY_AVAILABLE DESC, FITNESS_CERTIFICATE DESC;

/* End of script */